"""Add levels table and hierarchy changes

Revision ID: 2a964f2177a4
Revises: assessment_phase1
Create Date: 2025-12-17 16:25:12.663881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a964f2177a4'
down_revision: Union[str, Sequence[str], None] = 'assessment_phase1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_auto_grading_results_id'), 'auto_grading_results', ['id'], unique=False)
    op.add_column('micro_projects', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('micro_projects', sa.Column('requirements', sa.JSON(), nullable=True))
    op.add_column('micro_projects', sa.Column('evaluation_criteria', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_micro_projects_id'), 'micro_projects', ['id'], unique=False)
    op.create_foreign_key(None, 'micro_projects', 'levels', ['level_id'], ['id'])
    op.create_index(op.f('ix_project_submissions_id'), 'project_submissions', ['id'], unique=False)
    op.add_column('quiz_attempts', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_foreign_key(None, 'quiz_attempts', 'levels', ['level_id'], ['id'])
    op.add_column('quizzes', sa.Column('level_id', sa.Integer(), nullable=True))
    op.alter_column('quizzes', 'section_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'quizzes', 'levels', ['level_id'], ['id'])
    op.create_index(op.f('ix_topic_completions_id'), 'topic_completions', ['id'], unique=False)
    op.add_column('topics', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('topics', sa.Column('order_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'order_index')
    op.drop_column('topics', 'level_id')
    op.drop_index(op.f('ix_topic_completions_id'), table_name='topic_completions')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.alter_column('quizzes', 'section_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('quizzes', 'level_id')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_column('quiz_attempts', 'level_id')
    op.drop_index(op.f('ix_project_submissions_id'), table_name='project_submissions')
    op.drop_constraint(None, 'micro_projects', type_='foreignkey')
    op.drop_index(op.f('ix_micro_projects_id'), table_name='micro_projects')
    op.drop_column('micro_projects', 'evaluation_criteria')
    op.drop_column('micro_projects', 'requirements')
    op.drop_column('micro_projects', 'level_id')
    op.drop_index(op.f('ix_auto_grading_results_id'), table_name='auto_grading_results')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
