"""add_granular_mastery_metrics

Revision ID: 2e45f6abe603
Revises: 96b0096ee33a
Create Date: 2025-12-19 23:58:53.838578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e45f6abe603'
down_revision: Union[str, Sequence[str], None] = '96b0096ee33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_state', sa.Column('quiz_average', sa.Float(), nullable=True))
    op.add_column('learning_state', sa.Column('project_average', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_state', 'project_average')
    op.drop_column('learning_state', 'quiz_average')
    # ### end Alembic commands ###
