"""Add level_id to ProjectSubmission

Revision ID: 59842428dde5
Revises: 5c796ac88bdc
Create Date: 2025-12-18 23:22:43.902284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59842428dde5'
down_revision: Union[str, Sequence[str], None] = '5c796ac88bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_submissions', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project_submissions', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_submissions', type_='foreignkey')
    op.drop_column('project_submissions', 'level_id')
    # ### end Alembic commands ###
