"""Add ai_feedback

Revision ID: 5c796ac88bdc
Revises: 92ce8338a1ad
Create Date: 2025-12-18 19:03:34.339473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c796ac88bdc'
down_revision: Union[str, Sequence[str], None] = '92ce8338a1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_grading_results', sa.Column('ai_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_grading_results', 'ai_feedback')
    # ### end Alembic commands ###
