"""Add level_completions table

Revision ID: 92ce8338a1ad
Revises: 2a964f2177a4
Create Date: 2025-12-17 17:31:18.181197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ce8338a1ad'
down_revision: Union[str, Sequence[str], None] = '2a964f2177a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('project_score', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_completions_id'), 'level_completions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_level_completions_id'), table_name='level_completions')
    op.drop_table('level_completions')
    # ### end Alembic commands ###
