"""add_mastery_and_recommendations

Revision ID: 96b0096ee33a
Revises: 9935ee5f9bcf
Create Date: 2025-12-19 18:02:38.930123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b0096ee33a'
down_revision: Union[str, Sequence[str], None] = '9935ee5f9bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_state', sa.Column('mastery_score', sa.Float(), nullable=True))
    op.add_column('learning_state', sa.Column('mastery_level', sa.String(), nullable=True))
    op.add_column('learning_state', sa.Column('next_recommended_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_state', 'next_recommended_task_id')
    op.drop_column('learning_state', 'mastery_level')
    op.drop_column('learning_state', 'mastery_score')
    # ### end Alembic commands ###
