"""create_learning_state

Revision ID: 9935ee5f9bcf
Revises: af0b65bcaeac
Create Date: 2025-12-19 17:42:31.847820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9935ee5f9bcf'
down_revision: Union[str, Sequence[str], None] = 'af0b65bcaeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avg_tasks_per_week', sa.Float(), nullable=True),
    sa.Column('avg_time_to_pass_minutes', sa.Float(), nullable=True),
    sa.Column('retry_rate', sa.Float(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('current_velocity_band', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_state')
    # ### end Alembic commands ###
