"""Add skill_id and task_id to submissions

Revision ID: ad7167cdd08f
Revises: 59842428dde5
Create Date: 2025-12-19 16:27:38.134820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7167cdd08f'
down_revision: Union[str, Sequence[str], None] = '59842428dde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_submissions', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.add_column('project_submissions', sa.Column('task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'project_submissions', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_submissions', type_='foreignkey')
    op.drop_column('project_submissions', 'task_id')
    op.drop_column('project_submissions', 'skill_id')
    # ### end Alembic commands ###
