"""Add execution_profile

Revision ID: af0b65bcaeac
Revises: ad7167cdd08f
Create Date: 2025-12-19 17:01:33.206670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af0b65bcaeac'
down_revision: Union[str, Sequence[str], None] = 'ad7167cdd08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('micro_projects', sa.Column('execution_profile', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('execution_profile', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'execution_profile')
    op.drop_column('micro_projects', 'execution_profile')
    # ### end Alembic commands ###
