"""index_task_id_submissions

Revision ID: f2887d86aecd
Revises: 2e45f6abe603
Create Date: 2025-12-20 00:06:37.311447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2887d86aecd'
down_revision: Union[str, Sequence[str], None] = '2e45f6abe603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_submissions_task_id'), 'project_submissions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_submissions_task_id'), table_name='project_submissions')
    # ### end Alembic commands ###
